name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: "./app/build/outputs/apk/release/app-release-unsigned.apk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}